name: bazzite-scroll
description: My custom Bazzite OS with Scroll and Waybar

base-image: ghcr.io/ublue-os/bazzite
image-version: latest

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: rpm-ostree
    repos:
      - https://github.com/terrapkg/subatomic-repos/raw/main/terra.repo
    install:
      - scroll
      - xdg-desktop-portal-wlr
      - SwayNotificationCenter
      - network-manager-applet
      - blueman
      - swaylock
      - swayidle
      - playerctl
